// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1742615952);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1742615952);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{207f35d8-aa7e-41ae-b824-ec64fdc41f08}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1742615949);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 139);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2b27475a-75ca-4e5e-9fb0-eaab959a1619}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1742615950);
user_pref("browser.search.region", "CN");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20231009140911");
user_pref("browser.startup.homepage_override.mstone", "118.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1742615950);
user_pref("browser.topsites.contile.lastFetch", 1742615951);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "118.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231009140911");
user_pref("extensions.lastAppVersion", "118.0.2");
user_pref("extensions.lastPlatformVersion", "118.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9c34bece-e3a7-4dd4-bf7d-af8fd6d52eb4\",\"pictureinpicture@mozilla.org\":\"64a8172a-a852-4832-a9b3-b0d9dfbe1a1f\",\"screenshots@mozilla.org\":\"cba23799-50e6-4e4d-bae1-64ea9dedfd91\",\"webcompat-reporter@mozilla.org\":\"d7b8ded8-b1e2-46d0-91b2-d8bbb0f88bef\",\"webcompat@mozilla.org\":\"47823d4c-4f6a-40cb-aca2-bbbf28424262\",\"default-theme@mozilla.org\":\"02fb74df-91f6-4500-aceb-1765d80961eb\",\"addons-search-detection@mozilla.com\":\"a444af0d-b006-42bf-95f5-9e68e2f1428f\",\"google@search.mozilla.org\":\"e79fdb36-779d-431c-a933-a2998dbf58f4\",\"amazondotcom@search.mozilla.org\":\"29501d73-4ec8-4c1a-a036-e6803af38f8c\",\"wikipedia@search.mozilla.org\":\"81de1d00-f922-49ef-b1aa-f4a4f06c8411\",\"bing@search.mozilla.org\":\"b1a52679-5a57-4096-9290-a84e80640d05\",\"ddg@search.mozilla.org\":\"bcf67a0a-5fcb-4c74-8367-9941690fb355\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ebf80c11-caa7-4879-9e63-d30f64cd71ef");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1742615946);
user_pref("toolkit.telemetry.cachedClientID", "e0ec39e2-5c7d-4341-bf83-932763b0be1d");
user_pref("toolkit.telemetry.previousBuildID", "20231009140911");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
